Foreground yes
LogTime yes
LogFile /tmp/clamd.log
DatabaseDirectory /var/lib/clamav
LocalSocket /tmp/clamd.sock
TCPSocket 3310
TCPAddr 0.0.0.0
MaxThreads 4
StreamMaxLength 1024M
MaxFileSize 512M
MaxScanSize 1024M
AlertExceedsMax yes
