#!/usr/bin/env python3
"""Первичная сборка OWASP/findings/REGISTER.md (T-140) из прежних аудитов и ретеста 27.09.

Одноразовый генератор базовой линии: дальше REGISTER.md правится руками (он — источник истины),
а этот файл остаётся как запись о том, как посчитаны сводные числа 27.09.
Запуск: python3 OWASP/tooling/register_build.py > OWASP/findings/REGISTER.md
"""

from collections import Counter

# (реестр, прежний ID, источник, зона, тяжесть, суть, статус, основание 27.09, задача)
# статусы: open, open·частично, in-progress, fixed, verified, accepted, regression
T088 = "audits/2026-09-26-full-T088/report.md"
DB = "audits/2026-09-26-db-T104/report.md"
T129 = "audits/2026-09-27-s3-ml-T129/report.md"
NEW = "audits/2026-09-27-full-T140/"
E1, E2, E3 = (
    NEW + "expert-1-appsec-api.md",
    NEW + "expert-2-infra-supply-chain.md",
    NEW + "expert-3-ml-llm-docs-privacy.md",
)

ROWS = [
    # ---- T-088, 26.09 ----
    (
        "T088-H1",
        T088,
        "Z1",
        "HIGH",
        "reject с reason_code из прототипа — решение без журнала",
        "fixed",
        "E1: /decision закрыт, /reject-group нет → E1-M1; T-139 f460e68 закрывает оба (ветка)",
        "T-089, T-139",
    ),
    (
        "T088-H2",
        T088,
        "Z1",
        "HIGH",
        "За nginx один IP на всех: блокировка входа всем, IP прокси в журнале",
        "open",
        "E1: живой 429 на 900 с; эскалация на публичный демо → E1-H1",
        "T-090",
    ),
    (
        "T088-H3",
        T088,
        "Z4",
        "HIGH",
        "ML монтирует весь api-data (БД, токены)",
        "verified",
        "E2: только api-blobs:ro, секретов у ML нет",
        "T-091",
    ),
    (
        "T088-H4",
        T088,
        "Z1",
        "HIGH",
        "Демо-учётки с одним паролем в gpu",
        "verified",
        "E1, E2: gpu закрыт; демо в профиле dev → E2-H2",
        "T-092",
    ),
    (
        "T088-H5",
        T088,
        "Z6",
        "HIGH",
        "Раннер: учётка реестра в ~/.docker, push на все ветки",
        "open",
        "E2: спит (раннеров 0), конфиг не менялся",
        "T-093",
    ),
    (
        "T088-H6",
        T088,
        "Z7",
        "HIGH",
        "ReportLab без экранирования: инъекция разметки в PDF-протокол",
        "in-progress",
        "E3: подтверждено пробами на main; T-139 safe_markup.py (не закоммичено)",
        "T-094, T-139",
    ),
    (
        "T088-H7",
        T088,
        "Z6",
        "HIGH",
        "Вложенные actions qa-gate по тегу",
        "open",
        "E2: qa-standard@23ab9cf и HEAD — по тегу",
        "T-095",
    ),
    (
        "T088-M1",
        T088,
        "Z1",
        "MEDIUM",
        "BOLA/BOPLA: любая роль читает любую проверку, файлы, audit с IP",
        "in-progress",
        "E1: живая матрица 200; T-139 domain/access.ts (не закоммичено)",
        "T-139",
    ),
    (
        "T088-M2",
        T088,
        "Z1",
        "MEDIUM",
        "Admin проходит любую ролевую проверку",
        "in-progress",
        "E1: admin выносит решение 200; T-139 матрица прав",
        "T-139",
    ),
    (
        "T088-M3",
        T088,
        "Z1",
        "MEDIUM",
        "Опасные умолчания dev / rinMock / TLS off",
        "open·частично",
        "E1: gpu-compose задаёт mock=0; умолчания в коде прежние",
        "",
    ),
    (
        "T088-M4",
        T088,
        "Z1,Z7",
        "MEDIUM",
        "Нет ограничения ресурсов (rate limit, toBuffer, OCR, mem_limit)",
        "open·частично",
        "E1: limit/offset есть, rate limit нет; E3: PDF-потолки есть, TIFF/OOXML нет; E2-L4: mem_limit gpu нет",
        "",
    ),
    (
        "T088-M5",
        T088,
        "Z1",
        "MEDIUM",
        "CMS: SHA-1 даёт VALID, срок по signingTime, нет CRL/OCSP",
        "open",
        "E1: signature.ts:79,88,94",
        "",
    ),
    (
        "T088-M6",
        T088,
        "Z6",
        "MEDIUM",
        ".env, *.key, *.pfx не в .gitignore",
        "open",
        "E1, E2: git check-ignore — не игнорируются",
        "",
    ),
    (
        "T088-M7",
        T088,
        "Z5",
        "MEDIUM",
        "Плоская сеть с выходом, ML без аутентификации",
        "open·частично",
        "E2: сеть db internal; ML/Redis/RabbitMQ/ELK — с выходом (E2-M5), токена ML нет",
        "",
    ),
    (
        "T088-M8",
        T088,
        "Z7",
        "MEDIUM",
        "Redis без пароля, кэш разбора без HMAC",
        "open·частично",
        "E2, E3: TLS 1.3 есть; ACL/пароля и HMAC нет",
        "",
    ),
    (
        "T088-M9",
        T088,
        "Z6",
        "MEDIUM",
        "Гейт слеп: --ignore-unfixed, нет pnpm/pip audit, hadolint не в CI",
        "open·частично",
        "E2: hadolint только в local-gate; аудит зависимостей нет",
        "",
    ),
    (
        "T088-M10",
        T088,
        "Z6",
        "MEDIUM",
        "Нет SBOM/provenance/подписи, тег :sha перезаписывается",
        "open",
        "E2: ci-gate.yml:88-90; SBOM T-140 снят вручную",
        "",
    ),
    (
        "T088-M11",
        T088,
        "Z5",
        "MEDIUM",
        "Секреты через env",
        "open·частично",
        "E2: PG, брокер, S3 — файлами; Grafana/ELK — env",
        "",
    ),
    (
        "T088-M12",
        T088,
        "Z5",
        "MEDIUM",
        "RabbitMQ: administrator, management-плагин",
        "open·частично",
        "E2: пароль файлом; образ -management, тег administrator",
        "",
    ),
    (
        "T088-M13",
        T088,
        "Z1",
        "MEDIUM",
        "Успешный вход не сбрасывает счётчик",
        "open",
        "E1: живой 429 на верный пароль (app.ts:163)",
        "T-090",
    ),
    (
        "T088-M14",
        T088,
        "Z1",
        "MEDIUM",
        "Отклонённая загрузка оставляет проверку-сироту",
        "open",
        "E1: живой OBJ-ORPHAN PENDING",
        "",
    ),
    (
        "T088-M15",
        T088,
        "Z8",
        "MEDIUM",
        "Косвенная prompt injection через текст PDF (спит, provider=none)",
        "open",
        "E3: невидимый текст идёт в промпт; см. E3-H1",
        "",
    ),
    (
        "T088-M16",
        T088,
        "Z6",
        "MEDIUM",
        "pnpm без minimumReleaseAge, strictDepBuilds, trustPolicy",
        "open",
        "E2: pnpm-workspace.yaml только packages",
        "",
    ),
    (
        "T088-M17",
        T088,
        "Z6",
        "MEDIUM",
        "Ветки iter4/* с Vitest 3.2.7 без override qs",
        "open",
        "E2: 7 веток",
        "",
    ),
    (
        "T088-L1",
        T088,
        "Z1",
        "LOW",
        "500 вместо 4xx, request_id null",
        "open·частично",
        "E1: битый JSON в поле object → 500",
        "",
    ),
    (
        "T088-L2",
        T088,
        "Z1",
        "LOW",
        "Слабая валидация admin/ML (z.any, метрики вне [0,1])",
        "open",
        "E1: precision=2 → 200",
        "",
    ),
    (
        "T088-L3",
        T088,
        "Z7",
        "LOW",
        "regex_pattern без проверки → ReDoS под PDFIUM_LOCK",
        "open",
        "E1, E3: хуже — ML без аутентификации",
        "",
    ),
    (
        "T088-L4",
        T088,
        "Z1",
        "LOW",
        "sniff() принимает HTML/SVG как XML, отдаёт inline",
        "open",
        "E1: живой XHTML со script принят",
        "",
    ),
    (
        "T088-L5",
        T088,
        "Z1",
        "LOW",
        "Имена файлов с U+202E и 5000 символов",
        "open",
        "E1: живой — приняты",
        "",
    ),
    (
        "T088-L6",
        T088,
        "Z1",
        "LOW",
        "Управляющие символы в комментарии",
        "open·частично",
        "E1: NUL → 400, U+202E/BEL приняты",
        "",
    ),
    (
        "T088-L7",
        T088,
        "Z1,Z5",
        "LOW",
        "/health с ревизией наружу, /metrics без аутентификации",
        "open·частично",
        "E1, E2: /metrics → 404 в nginx; /health наружу",
        "",
    ),
    (
        "T088-L8",
        T088,
        "Z1",
        "LOW",
        "Внутренние адреса ML в ошибках 502",
        "open",
        "E1: ml-client.ts:76,125,157",
        "",
    ),
    (
        "T088-L9",
        T088,
        "Z1",
        "LOW",
        "Сессии без тайм-аута бездействия, scrypt N=2^14",
        "open·частично",
        "E1: истёкшие чистятся; остальное прежнее",
        "",
    ),
    (
        "T088-L10",
        T088,
        "Z1",
        "LOW",
        "API сам не ставит заголовки безопасности",
        "open·частично",
        "E1: за nginx есть, у API нет",
        "",
    ),
    (
        "T088-L11",
        T088,
        "Z1",
        "LOW",
        "OpenAPI покрывал 22 из 59 операций",
        "verified",
        "E1: 66/66, храповик пуст",
        "T-026",
    ),
    (
        "T088-L12",
        T088,
        "Z6",
        "LOW",
        ".dockerignore исключает секреты только в корне",
        "open",
        "E2: без **/; шире — .secrets/, INPUT/, ТЗ/ не исключены (E2-L1)",
        "",
    ),
    (
        "T088-L13",
        T088,
        "Z5",
        "LOW",
        "Общий server.key у web и api",
        "regression",
        "E2: теперь один ключ у шести сервисов gpu",
        "",
    ),
    (
        "T088-L14",
        T088,
        "Z5",
        "LOW",
        "Kibana только под elastic",
        "open",
        "E2: роли читателя нет",
        "",
    ),
    (
        "T088-L15",
        T088,
        "Z2",
        "LOW",
        "nginx: нет Permissions-Policy, COOP/CORP; style-src unsafe-inline",
        "open",
        "E2: живой ответ демо",
        "",
    ),
    (
        "T088-L16",
        T088,
        "Z8",
        "LOW",
        "Вывод LLM не ограничен",
        "open",
        "E3: advisor.py:168-178",
        "",
    ),
    (
        "T088-L17",
        T088,
        "Z8",
        "LOW",
        "Ответы ML в API не проверяются схемой",
        "open",
        "E3: advisor.ts:47, ml-client.ts",
        "",
    ),
    (
        "T088-L18",
        T088,
        "Z8",
        "LOW",
        "Контекст советника молча обрезается",
        "open",
        "E3: advisor.py:70",
        "",
    ),
    (
        "T088-L19",
        T088,
        "Z8",
        "LOW",
        "Нет маркировки ИИ (2078-ПП): нормы, советник, VLM",
        "open",
        "E1, E3: шире — нет VLM и читателей сканов",
        "",
    ),
    (
        "T088-L20",
        T088,
        "Z8",
        "LOW",
        "URL Ollama принимает любой http://",
        "open",
        "E3; bandit B310 ×3 (_http.py, vlm.py)",
        "",
    ),
    (
        "T088-L21",
        T088,
        "Z6",
        "LOW",
        "Мелочи цепочки поставок",
        "open·частично",
        "E2: packageManager с хешем; pip uninstall || true",
        "",
    ),
    # ---- аудит БД, 26.09 ----
    (
        "DB-HIGH-1",
        DB,
        "Z4",
        "HIGH",
        "API — суперпользователь кластера",
        "verified",
        "E2: роли owner/migrator/app",
        "T-107",
    ),
    (
        "DB-HIGH-2",
        DB,
        "Z4",
        "HIGH",
        "Журнал аудита не append-only",
        "verified",
        "E2: триггеры на 4 журналах + 0003/0004; обход суперпользователем — E2-L6",
        "T-107",
    ),
    (
        "DB-HIGH-3",
        DB,
        "Z4",
        "HIGH",
        "Токены сессий открытым текстом",
        "verified",
        "E1 живой, E2 код",
        "T-107",
    ),
    (
        "DB-HIGH-4",
        DB,
        "Z4",
        "HIGH",
        "Демо-учётки и пароль на томе ML в gpu",
        "verified",
        "E2: для gpu; демо в dev → E2-H2",
        "T-107",
    ),
    (
        "DB-M-1",
        DB,
        "Z4",
        "MEDIUM",
        "Нет TLS до БД",
        "verified",
        "E2: TLS 1.3, hostnossl reject",
        "T-107",
    ),
    (
        "DB-M-2",
        DB,
        "Z4",
        "MEDIUM",
        "Таймауты и выборки без лимита",
        "verified",
        "E1, E2",
        "T-107",
    ),
    (
        "DB-M-3",
        DB,
        "Z1",
        "MEDIUM",
        "NUL → 500",
        "verified",
        "E1 живой 400; соседние коды 22xxx → E1-L3",
        "T-107",
    ),
    ("DB-M-4", DB, "Z4", "MEDIUM", "Нет CHECK", "verified", "E2: 19 check", "T-107"),
    (
        "DB-M-5",
        DB,
        "Z4",
        "MEDIUM",
        "Журнал миграций правится",
        "verified",
        "E2: миграции только api-migrate",
        "T-107",
    ),
    (
        "DB-M-6",
        DB,
        "Z4",
        "MEDIUM",
        "ПДн в журналах без минимизации и срока",
        "open·частично",
        "E1: логин хешируется; E2: срока хранения и шифрования тома нет",
        "T-071",
    ),
    (
        "DB-M-7",
        DB,
        "Z4",
        "MEDIUM",
        "Финализированный протокол изменяем",
        "verified",
        "E1, E2",
        "T-107",
    ),
    (
        "DB-M-8",
        DB,
        "Z4",
        "MEDIUM",
        "База в сети с выходом",
        "verified",
        "E2: db internal во всех контурах",
        "T-107",
    ),
    (
        "DB-M-9",
        DB,
        "Z4",
        "MEDIUM",
        "Сервер БД не журналирует события безопасности",
        "open·частично",
        "E2: логи есть, в индекс безопасности не попадают (E2-M4)",
        "",
    ),
    (
        "DB-M-10",
        DB,
        "Z4",
        "MEDIUM",
        "Нет бэкапа и PITR",
        "open",
        "E2: WAL-архива нет",
        "T-072",
    ),
    (
        "DB-L-1",
        DB,
        "Z4",
        "LOW",
        "redactUrl не скрывает ?password=",
        "open",
        "E1, E2",
        "",
    ),
    (
        "DB-L-2",
        DB,
        "Z4",
        "LOW",
        "release после сбоя rollback",
        "verified",
        "E1, E2",
        "T-107",
    ),
    (
        "DB-L-3",
        DB,
        "Z4",
        "LOW",
        "LIKE без экранирования",
        "open",
        "E1, E2: sheetdiff.ts:26",
        "",
    ),
    ("DB-L-4", DB, "Z4", "LOW", "Нет FK", "open", "E2", ""),
    ("DB-L-5", DB, "Z4", "LOW", "Индексы под горячие запросы", "open", "E2", ""),
    ("DB-L-6", DB, "Z4", "LOW", "trust и PUBLIC на БД", "verified", "E2", "T-107"),
    ("DB-L-7", DB, "Z4", "LOW", "Один секрет на всех", "verified", "E2", "T-107"),
    (
        "DB-L-8",
        DB,
        "Z4",
        "LOW",
        "json без схемы и размера",
        "open",
        "E1, E2 (= T088-L2)",
        "",
    ),
    (
        "DB-L-9",
        DB,
        "Z4",
        "LOW",
        "scrypt ниже рекомендации OWASP",
        "open",
        "E1, E2 (= T088-L9)",
        "",
    ),
    (
        "DB-L-10",
        DB,
        "Z4",
        "LOW",
        "Режим паритета опасен в gpu",
        "open",
        "E2: риск низкий, ветка недостижима в gpu",
        "",
    ),
    # ---- T-129, 27.09 ----
    (
        "T129-SEC-01",
        T129,
        "Z7",
        "MEDIUM",
        "Растр недоверенного PDF без потолка",
        "verified",
        "E3: для PDF; обход через TIFF → E3-M2",
        "T-129",
    ),
    (
        "T129-SEC-02",
        T129,
        "Z7",
        "MEDIUM",
        "Отсев VLM прячет противоречие",
        "verified",
        "E3: с оговоркой к E3-H1",
        "T-129",
    ),
    (
        "T129-SEC-03",
        T129,
        "Z7",
        "LOW",
        "Число вызовов судьи VLM не ограничено",
        "verified",
        "E3: MAX_JUDGE_CALLS=30",
        "T-129",
    ),
    (
        "T129-SEC-04",
        T129,
        "Z1",
        "LOW",
        "Вердикт верификации по клиентскому ok",
        "verified",
        "E1 живой",
        "T-129",
    ),
    (
        "T129-SEC-05",
        T129,
        "Z1",
        "LOW",
        "Application/JSON обходил схему",
        "verified",
        "E1 живой",
        "T-129",
    ),
    (
        "T129-SEC-06",
        T129,
        "Z1",
        "LOW",
        "500 с деталями ответа наружу",
        "verified",
        "E1 живой",
        "T-129",
    ),
    (
        "T129-SEC-07",
        T129,
        "Z5",
        "LOW",
        "Пароль брокера в env",
        "verified",
        "E2",
        "T-129",
    ),
    (
        "T129-SEC-08",
        T129,
        "Z5",
        "LOW",
        "Сеть edge стенда не internal",
        "accepted",
        "E2: принятый риск; на демо не пересмотрен",
        "T-129",
    ),
    (
        "T129-SEC-09",
        T129,
        "Z3",
        "LOW",
        "http:// к S3, VLM, в CLI",
        "verified",
        "E2 (S3), E3 (VLM)",
        "T-129",
    ),
    (
        "T129-SEC-10",
        T129,
        "Z1",
        "LOW",
        "--param в имени выходного файла",
        "verified",
        "E1: load-package.test.ts",
        "T-129",
    ),
    (
        "T129-SEC-11",
        T129,
        "Z4",
        "INFO",
        "Ключ объекта = SHA-256 открытого текста",
        "accepted",
        "E2: ADR-0006",
        "T-129",
    ),
    (
        "T129-SEC-12",
        T129,
        "Z6",
        "INFO",
        "packageManager без хеша",
        "verified",
        "E2",
        "T-129",
    ),
    (
        "T129-SEC-13",
        T129,
        "Z3",
        "INFO",
        "CONNECT без тайм-аута, учётные данные прокси в ошибке",
        "verified",
        "ведущий: s3-proxy.test.ts 4/4 зелёные",
        "T-129",
    ),
    # ---- T-140, новые (после дедупликации) ----
    (
        "E1-H1",
        E1,
        "Z1,Z5",
        "HIGH",
        "Аноним 20 входами закрывает вход всем на 15 мин — на публичном демо",
        "open",
        "живой 429/900 с; эскалация T088-H2",
        "T-090",
    ),
    (
        "E2-H1",
        E2,
        "Z3,Z4",
        "HIGH",
        "Засвеченный S3-ключ на весь бакет + единственный AES-ключ на публичном hk-ru, нет key_id",
        "open",
        "T-108, sha256 ключей совпадают",
        "T-144",
    ),
    (
        "E2-H2",
        E2,
        "Z1,Z5",
        "HIGH",
        "Реальный пакет с ФИО/подписями на демо без пароля прокси, профиль dev, общие учётки (+E1-M3)",
        "open",
        "ADR-0006 п.6, Caddyfile, живой 200",
        "T-143",
    ),
    (
        "E3-H1",
        E3,
        "Z7",
        "HIGH",
        "Невидимый текст PDF подменяет значение параметра",
        "open",
        "синтетика: видно С2 → извлечено С0 с уверенностью 1.0",
        "T-149",
    ),
    (
        "E1-M1",
        E1,
        "Z1",
        "MEDIUM",
        "/reject-group принимает reason_code «constructor», /ml/report падает 500",
        "fixed",
        "T-139 f460e68 (ветка)",
        "T-139",
    ),
    (
        "E1-M2",
        E1,
        "Z1,Z8",
        "MEDIUM",
        "Шлюз публикации модели верит метрикам клиента",
        "open",
        "живой: фейковая модель стала текущей",
        "",
    ),
    (
        "E2-M1",
        E2,
        "Z6",
        "MEDIUM",
        "Нет защиты веток и исполняемого CI, демо-образы мимо гейта",
        "open",
        "GitHub API 403, раннеров 0",
        "",
    ),
    (
        "E2-M2",
        E2,
        "Z5",
        "MEDIUM",
        "Публичный вход принимает TLS 1.2 (ТЗ 12.3 — 1.3)",
        "open",
        "openssl s_client -tls1_2 к демо",
        "T-071",
    ),
    (
        "E2-M4",
        E2,
        "Z5",
        "MEDIUM",
        "Нет алертов безопасности, события PG не в годовом индексе",
        "open",
        "alerts.yml, inspector.conf:69-75",
        "",
    ),
    (
        "E2-M6",
        E2,
        "Z6",
        "MEDIUM",
        "security-guard.yml: checkout@v4 по тегу в pull_request_target",
        "open",
        "security-guard.yml",
        "T-095",
    ),
    (
        "E3-M1",
        E3,
        "Z7",
        "MEDIUM",
        "Сборка строк сверхлинейна и под PDFIUM_LOCK (51 с на 8000 слов)",
        "open",
        "проба на синтетике",
        "",
    ),
    (
        "E3-M2",
        E3,
        "Z7",
        "MEDIUM",
        "TIFF без потолка кадров, OOXML без потолка распаковки",
        "open",
        "TIFF 5000 кадров = 720 КБ",
        "",
    ),
    (
        "E3-M3",
        E3,
        "Z6,Z7",
        "MEDIUM",
        "Веса VLM без ревизии и хеша (+E2-M3)",
        "open",
        "models.yaml, vlm.py",
        "",
    ),
    (
        "E3-M4",
        E3,
        "Z8",
        "MEDIUM",
        "Полный текст документов с ПДн в кэшах ML без срока",
        "open",
        "ml-cache, Redis 30 дней, audit_log",
        "T-074",
    ),
    (
        "E1-L1",
        E1,
        "Z1",
        "LOW",
        "Проверка схемы раньше аутентификации",
        "in-progress",
        "T-139: auth на onRequest (не закоммичено)",
        "T-139",
    ),
    (
        "E1-L2",
        E1,
        "Z1",
        "LOW",
        "Гостевой вход можно направить на admin",
        "open",
        "",
        "",
    ),
    (
        "E1-L3",
        E1,
        "Z1",
        "LOW",
        "22007/22P02 → 500 и critical-алерт",
        "open",
        "живой /ml/report?since=not-a-date",
        "",
    ),
    ("E1-L4", E1, "Z1", "LOW", "Недоступный ML → 500 вместо 502/503", "open", "", ""),
    (
        "E1-L5",
        E1,
        "Z2",
        "LOW",
        "/docs на том же origin с script-src unsafe-inline (+E2-L3)",
        "open",
        "",
        "",
    ),
    (
        "E1-L6",
        E1,
        "Z1",
        "LOW",
        "Групповое снятие и перевод гипотезы не атомарны",
        "fixed",
        "T-139 f460e68: группа целиком",
        "T-139",
    ),
    (
        "E1-L7",
        E1,
        "Z1",
        "LOW",
        "Файлы inline без собственных защитных заголовков",
        "open",
        "",
        "",
    ),
    (
        "E2-L2",
        E2,
        "Z5",
        "LOW",
        "Grafana→Prometheus→Alertmanager по HTTP",
        "open",
        "",
        "",
    ),
    (
        "E2-L5",
        E2,
        "Z5",
        "LOW",
        "Секреты демо на хосте с правами 644",
        "open",
        "scripts/demo.sh:87",
        "T-143",
    ),
    (
        "E2-L6",
        E2,
        "Z4",
        "LOW",
        "Публикация демо восстанавливает данные в обход append-only",
        "open",
        "",
        "T-143",
    ),
    (
        "E2-L7",
        E2,
        "Z6",
        "LOW",
        "Мёртвые исключения .gitleaksignore (7 при 0 срабатываний)",
        "open",
        "gitleaks с/без ignore = 0",
        "",
    ),
    (
        "E3-L1",
        E3,
        "Z7",
        "LOW",
        "/measure разбирает документ заново мимо кэша",
        "open",
        "",
        "",
    ),
    ("E3-L2", E3, "Z8", "LOW", "Кэш эмбеддингов Ollama без предела", "open", "", ""),
    (
        "E3-L3",
        E3,
        "Z7",
        "LOW",
        "Текст исключения судьи VLM в карточке инспектора",
        "open",
        "",
        "",
    ),
]

MERGED = [
    ("E1-M3", "E2-H2", "демо в профиле dev с общими учётками"),
    ("E2-M3", "E3-M3", "веса VLM без ревизии"),
    ("E2-L3", "E1-L5", "/docs с unsafe-inline"),
    ("E2-M5", "T088-M7", "плоская сеть gpu"),
    ("E2-L1", "T088-L12", ".dockerignore"),
    ("E2-L4", "T088-M4", "mem_limit gpu"),
]

ORDER = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
OPEN = {"open", "open·частично", "in-progress", "fixed", "regression"}


def main() -> None:
    ids = [r[0] for r in ROWS]
    assert len(ids) == len(set(ids)), "дубли ID"
    out = []
    w = out.append
    w(
        '---\nid: OWASP-REGISTER\ntitle: "Единый реестр OWASP-находок"\ntype: register\nowner: almazrobots\nstatus: current'
    )
    w(
        "created: 2026-09-27\nupdated: 2026-09-27\ntask: T-140\nbaseline_commit: 66593fa\n---\n"
    )
    w("# Единый реестр OWASP-находок\n")
    w(
        "**Источник истины о статусе** любой находки любого аудита. Отчёты фиксируют срез и не правятся; статус меняется здесь."
    )
    w(
        "Жизненный цикл и сроки — [`MEGAPLAN.md`](../MEGAPLAN.md) §8. Базовая линия собрана `tooling/register_build.py` по ретесту"
    )
    w("полного аудита T-140 (27.09, `main` 66593fa); дальше таблица правится руками.\n")
    w(
        "Статусы: `open` · `open·частично` (часть закрыта, остаток открыт) · `in-progress` (фикс в ветке, не закоммичен) ·"
    )
    w(
        "`fixed` (фикс закоммичен в ветке, ждёт влития и ретеста) · `verified` (ретест на `main` подтвердил) · `accepted` (принятый"
    )
    w("риск) · `regression` (закрытое вернулось).\n")
    # сводка
    new = [r for r in ROWS if r[0][:2] in ("E1", "E2", "E3")]
    prior = [r for r in ROWS if r not in new]
    w("## Сводка на 27.09\n")
    w(
        "| Тяжесть | Всего | Открыто (open, частично, in-progress, fixed, regression) | verified | accepted |"
    )
    w("|---|---|---|---|---|")
    for sev in ORDER:
        rs = [r for r in ROWS if r[3] == sev]
        if not rs:
            continue
        w(
            f"| {sev} | {len(rs)} | {sum(r[5] in OPEN for r in rs)} | {sum(r[5] == 'verified' for r in rs)} | {sum(r[5] == 'accepted' for r in rs)} |"
        )
    w(
        f"| **Итого** | **{len(ROWS)}** | **{sum(r[5] in OPEN for r in ROWS)}** | **{sum(r[5] == 'verified' for r in ROWS)}** | **{sum(r[5] == 'accepted' for r in ROWS)}** |\n"
    )
    c = Counter(r[5] for r in prior)
    w(
        f"Прежние находки ({len(prior)}: T-088 — 45, БД — 24, T-129 — 13), ретест 27.09: "
        + ", ".join(f"`{k}` {v}" for k, v in sorted(c.items()))
        + "."
    )
    cn = Counter(r[3] for r in new)
    w(
        f"Новые находки T-140 после дедупликации: {len(new)} ("
        + ", ".join(f"{k} {cn[k]}" for k in ORDER if cn[k])
        + f"); слито дублей — {len(MERGED)}.\n"
    )
    # таблица
    w("## Находки\n")
    w(
        "| Реестр | ID | Зона | Тяжесть | Суть | Статус | Основание (ретест 27.09) | Задача | Источник |"
    )
    w("|---|---|---|---|---|---|---|---|---|")
    for n, r in enumerate(
        sorted(
            ROWS,
            key=lambda r: (
                ORDER[r[3]],
                r[5] == "verified",
                r[5] == "accepted",
                ids.index(r[0]),
            ),
        ),
        1,
    ):
        pid, src, zone, sev, what, st, why, task = r
        reg = f"OWASP-{ids.index(pid) + 1:04d}"
        w(
            f"| {reg} | {pid} | {zone} | {sev} | {what} | `{st}` | {why} | {task} | [отчёт](../{src}) |"
        )
    w(
        "\nНомер `OWASP-NNNN` постоянный и не переиспользуется; порядок строк — тяжесть, затем открытые выше закрытых.\n"
    )
    w("## Слитые дубли\n")
    w("| ID эксперта | Слит в | Что |\n|---|---|---|")
    for a, b, what in MERGED:
        w(f"| {a} | {b} | {what} |")
    print("\n".join(out))


if __name__ == "__main__":
    main()
