-- 0001 — базовая схема «Инспектора ИИ» в PostgreSQL (ADR-0003, T-107). Имена таблиц и колонок — по ТЗ §10.
-- Перенос схемы SQLite 1:1 вместе с колонками, которые досоздавались addColumns/migrate, в родных типах:
--   системные отметки времени (пишет сама система) — timestamptz; даты из внешних источников и реестров — text,
--     как пришли (approval_date, date, effective_from/to, rin_created_at, event_at, since/until);
--   флаги — boolean; JSON — json (текст хранится байт в байт: хеши и подписи протоколов не плывут);
--   суррогатные ключи — bigint identity; доли и метрики — double precision.
-- Миграция неизменяема: правка — только новым файлом 000N_*.sql (контрольная сумма сверяется при старте).

create table meta (key text primary key, value text not null);

create table users (
  id text primary key, login text unique not null, name text not null, role text not null, password_hash text not null);

create table sessions (
  token text primary key, user_id text not null references users(id), created_at timestamptz not null, expires_at timestamptz not null);
create index ix_sessions_expires on sessions(expires_at);

create table objects (
  id text primary key, name text not null, address text, customer text, contractor text, permit_number text,
  profile_json json not null default '{}', created_at timestamptz not null);

create table inspections (
  id text primary key, object_id text not null references objects(id), status text not null, scenario text,
  load_codes_json json, manifest_json json, manifest_hash text, input_manifest_hash text,
  protocol_version integer not null default 0, sync_status text, created_by text,
  created_at timestamptz not null, updated_at timestamptz not null, finalized_at timestamptz);
create index ix_insp_object on inspections(object_id);

create table files (
  id text primary key, inspection_id text not null references inspections(id), object_id text not null,
  client_file_id text not null, file_name text not null, sha256 text not null, size bigint not null, kind text not null,
  doc_stage text not null, discipline text, document_code text not null, revision text not null,
  approval_status text, approval_date text, predecessor_id text, successor_id text, signature_status text, sheet_page_range text,
  revision_role text, revision_note text, parse_status text not null default 'PENDING', parse_attempts integer not null default 0,
  parse_error text, pages_json json, engine text, uploaded_at timestamptz not null,
  part_of text, part_index integer, page_offset integer, doc_title text,
  doc_type text, doc_type_json json, signature_check_json json,
  unique (inspection_id, client_file_id));
create index ix_files_insp on files(inspection_id);
create index ix_files_object on files(object_id);

create table extractions (
  id bigint generated by default as identity primary key, file_id text not null references files(id), param_code text not null,
  kind text not null, raw text, value_num double precision, value_text text, page integer, bbox_json json, anchor_bbox_json json,
  line_text text, confidence double precision);
create index ix_extr_file on extractions(file_id);
create index ix_extr_param on extractions(param_code);

create table rooms (
  id bigint generated by default as identity primary key, file_id text not null references files(id), number text, name text,
  page integer, bbox_json json);
create index ix_rooms_file on rooms(file_id);

create table params (
  id integer primary key, code text unique not null, section text not null, parameter_name text not null, unit text,
  source_pd text, source_rd text, source_id text, trigger_logic text, review_priority text,
  sp_reference text, gost_reference text, fz_reference text, other_normative text,
  data_type text not null, compare_json json not null, anchors_json json not null, regex_pattern text, value_scale_json json,
  applicability text, min_value double precision, max_value double precision, is_active boolean not null default true,
  created_at timestamptz not null, updated_at timestamptz not null);

create table checks (
  id text primary key, inspection_id text not null references inspections(id), param_code text not null, evidence_group_id text not null,
  finding_status text not null, verification_status text not null default 'PENDING', expected_value text, actual_value text, delta text,
  review_priority text, reason text, stage_notes_json json, parent_id text, title text,
  computed_in_version integer not null, created_at timestamptz not null, updated_at timestamptz not null,
  ai_score double precision);
create index ix_checks_insp on checks(inspection_id);

create table evidence_fragments (
  id bigint generated by default as identity primary key, check_id text not null references checks(id) on delete cascade,
  file_id text not null, sha256 text, stage text, document_code text, revision text, approval_status text, sheet_page integer,
  bbox_polygon_norm text, extracted_value text, role_expected_actual text);
create index ix_frag_check on evidence_fragments(check_id);

-- Решение — след аудита: переживает проверку, пересчитанную заново (hidden-works, requisites), поэтому без FK на checks.
create table decisions (
  id bigint generated by default as identity primary key, check_id text not null, user_id text not null,
  action text not null, status text not null, reason_code text, comment text, created_at timestamptz not null,
  superseded boolean not null default false);
create index ix_decisions_check on decisions(check_id);

create table suspicions (
  id bigint generated by default as identity primary key, inspection_id text not null references inspections(id), object_id text not null,
  discovery_method text not null, confidence double precision, description text, pd_reference text, rd_reference text,
  review_priority text, normative_base text,
  finding_status text not null default 'SUSPICION', inspector_status text not null default 'PENDING', dedup_key text not null,
  advisor_ref_json json, promoted_check_id text,
  unique (inspection_id, dedup_key));

create table logical_rules (
  id bigint generated by default as identity primary key, rule_name text not null, condition_json json not null,
  expected_json json not null, fact_anchors_json json not null default '[]', normative_base text,
  is_active boolean not null default true);

create table normative_base (
  id bigint generated by default as identity primary key, document_name text not null, document_number text not null, section text,
  parameter_name text, param_code text, min_value double precision, max_value double precision, effective_from text, effective_to text,
  is_active boolean not null default true);

create table protocols (
  id bigint generated by default as identity primary key, inspection_id text not null references inspections(id), version integer not null,
  matrix_version text, dataset_version text, model_version text, input_manifest_hash text, status text not null,
  body_json json not null, created_at timestamptz not null, finalized_at timestamptz,
  unique (inspection_id, version));

create table sync_jobs (
  id bigint generated by default as identity primary key, inspection_id text not null references inspections(id),
  protocol_version integer not null, status text not null, attempts integer not null default 0, next_attempt_at timestamptz,
  last_error text, created_at timestamptz not null, updated_at timestamptz not null);
create index ix_sync_due on sync_jobs(status, next_attempt_at);

create table rin_packages (
  package_id text primary key, object_id text not null, inspection_id text, status text not null, reason text,
  rin_created_at text, attempts integer not null default 0, fetched_at timestamptz, updated_at timestamptz not null);

create table audit_log (
  id bigint generated by default as identity primary key, user_id text, action text not null, object_id text, details text,
  timestamp timestamptz not null, ip_address text, user_agent text);
create index ix_audit_object on audit_log(object_id);
create index ix_audit_ts on audit_log(timestamp);

create table notifications (
  id bigint generated by default as identity primary key, user_role text not null, inspection_id text, level text not null,
  message text not null, created_at timestamptz not null, read boolean not null default false);

create table dataset_versions (
  id bigint generated by default as identity primary key, dataset_version text unique not null, split_hashes_json json not null,
  items integer not null, positives integer not null, negatives integer not null, created_by text, created_at timestamptz not null);

create table dataset_items (
  id bigint generated by default as identity primary key, dataset_version text not null references dataset_versions(dataset_version),
  evidence_group_id text not null, finding_id text not null, gold_label text not null, expert_id text, reason_code text,
  split text not null, object_group_id text not null);
create index ix_ditems_version on dataset_items(dataset_version);

create table approved_changes (
  id bigint generated by default as identity primary key, inspection_id text not null references inspections(id), object_id text not null,
  number text not null, date text not null, param_codes_json json not null, basis_file_id text, description text not null default '',
  created_by text not null, created_at timestamptz not null);
create index ix_changes_obj on approved_changes(object_id);

create table hidden_works (
  id bigint generated by default as identity primary key, file_id text not null references files(id), n integer not null,
  text text not null, page integer, bbox_json json);
create index ix_hw_file on hidden_works(file_id);

create table retraining_reports (
  id bigint generated by default as identity primary key, since text not null, until text not null unique, body_json json not null,
  created_at timestamptz not null);

create table rejection_log (
  id bigint generated by default as identity primary key, check_id text not null, inspection_id text not null, param_code text not null,
  ai_verdict text not null, reason_code text not null, comment text not null, suggested_fix text not null, user_id text not null,
  created_at timestamptz not null);
create index ix_rejection_insp on rejection_log(inspection_id);

create table dispute_log (
  id bigint generated by default as identity primary key, check_id text not null, inspection_id text not null, param_code text not null,
  kind text not null, ai_comment text not null, inspector_comment text not null, user_id text not null, created_at timestamptz not null);
create index ix_dispute_insp on dispute_log(inspection_id);

create table legal_acts (
  n integer primary key, short text not null, kind text not null, title text not null, number text not null,
  date text, edition text, edition_date text, note text);

create table requisites (
  id bigint generated by default as identity primary key, file_id text not null references files(id), page integer not null,
  kind text not null, bbox_json json, confidence double precision not null);
create index ix_req_file on requisites(file_id);

create table model_versions (
  id bigint generated by default as identity primary key, model_version text unique not null, artifact_hash text, dataset_version text,
  metrics_json json, approval_status text not null, approved_by text, deployed_at timestamptz, rollback_to text,
  created_at timestamptz not null,
  -- OS-INSP-6.4.5: реестр итераций дообучения
  matrix_version text, split_hashes_json json, training_code_hash text, training_params_json json, weights_json json,
  weights_hash text, per_category_metrics_json json, trained_by text, previous_model text, gate_json json);

create table prescriptions (
  id bigint generated by default as identity primary key, inspection_id text not null references inspections(id),
  prescription_id text not null, current_status text not null, current_event_at text not null,
  created_at timestamptz not null, updated_at timestamptz not null,
  unique (inspection_id, prescription_id));

create table prescription_events (
  id bigint generated by default as identity primary key, prescription_ref bigint not null references prescriptions(id),
  prescription_id text not null, status text not null, event_at text not null, received_at timestamptz not null,
  unique (prescription_ref, status, event_at));

-- NFR-METRICS-STORE (ТЗ §10 п. 13): снимки метрик производительности
create table monitoring_metrics (
  id bigint generated by default as identity primary key, metric_name text not null, value double precision not null,
  timestamp timestamptz not null, service_name text not null, tags json not null default '{}');
create index ix_metrics_name_ts on monitoring_metrics(metric_name, timestamp);
create index ix_metrics_ts on monitoring_metrics(timestamp);
