-- 0003 — совпадения выборкой (T-110; кандидаты OS-INSP-4.1.8–4.1.11, карта сценариев SC-04).
-- Акт приёмки партии системных «расхождения нет» по случайной выборке: кто, когда, seed, объём партии и выборки,
-- верхняя граница доли ошибок, состав выборки и партии. Журнал только дописывается (как audit_log в 0002).
-- Миграция неизменяема: правка — только новым файлом.

create table sample_acceptances (
  id bigint generated by default as identity primary key,
  inspection_id text not null references inspections(id),
  user_id text not null,
  seed bigint not null,
  pool_size integer not null check (pool_size >= 0),
  sample_size integer not null check (sample_size >= 0 and sample_size <= pool_size),
  upper_bound double precision not null check (upper_bound >= 0 and upper_bound <= 1),
  sample_ids json not null,
  pool_ids json not null,
  created_at timestamptz not null
);
create index ix_sample_acceptances_insp on sample_acceptances(inspection_id);

create trigger sample_acceptances_append_only before update or delete on sample_acceptances for each row execute function forbid_mutation();
create trigger sample_acceptances_no_truncate before truncate on sample_acceptances for each statement execute function forbid_mutation();

-- права роли API (сервер): акт приёмки только дописывается и читается
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'inspector_app') then
    grant select, insert on sample_acceptances to inspector_app;
    revoke update, delete, truncate on sample_acceptances from inspector_app;
  end if;
end $$;
