-- 0004 — М-023 сквозь систему (T-129; OS-INSP-2.2.13–2.2.16, 3.1.10–3.1.15, 6.5.8, 7.1.4).
-- 1) Упоминание значения несёт метаданные: ограничение «не ниже», причина отсева, цитата, операции каталога.
-- 2) Доказательная группа хранит provenance: операции каталога и все найденные упоминания стадий.
-- 3) Результаты автоматической верификации параметра (независимый пересчёт) — журнал, только дописывается.
-- 4) М-023 получает порядковую шкалу С3 < С2 < С1 < С0; в уже засеянной базе Матрица поднимается до 1.1.1.
-- Миграция неизменяема: правка — только новым файлом.

alter table extractions add column meta_json json;
alter table checks add column provenance_json json;

create table param_verifications (
  id bigint generated by default as identity primary key,
  param_code text not null,
  inspection_id text references inspections(id),
  object_id text,
  verdict text not null check (verdict in ('MATCH', 'MISMATCH')),
  fields_json json not null,
  method text not null,
  checked_at timestamptz not null
);
create index ix_param_verifications_code on param_verifications(param_code, checked_at desc);
create trigger param_verifications_append_only before update or delete on param_verifications for each row execute function forbid_mutation();

update params set data_type = 'enum', value_scale_json = '["С3","С2","С1","С0"]'::json, unit = 'Класс (С0–С3)', updated_at = now()
  where code = 'M-023';
update meta set value = '1.1.1' where key = 'matrix_version' and value = '1.1.0' and exists (select 1 from params where code = 'M-023');
