-- 0007 — печать скрытого теста и журнал ответов (T-137; OS-INSP-6.1.4–6.1.7; ТЗ 14.2-04, 9.4.2-03).
--   hidden_seals     — печать: SHA-256 каждого файла с ролью input/labels (files_json, без путей) и общий отпечаток
--                      (канон — domain/hidden-seal.ts, паритет с ml/eval/hidden_seal.py);
--   hidden_seal_runs — журнал ответов, записанных до подсчёта балла по меткам (SHA-256 ответа, версия модели, время).
-- Обе таблицы только дописываются: триггеры 0002 (forbid_mutation) и отзыв прав у роли API.
-- Миграция неизменяема: правка — только новым файлом.

create table hidden_seals (
  name text primary key check (name ~ '^[A-Za-z0-9._-]{1,100}$' and name not in ('.', '..')),
  digest text not null check (digest ~ '^[0-9a-f]{64}$'),
  files_json json not null,
  n_files integer not null check (n_files > 0),
  n_labels integer not null check (n_labels >= 0 and n_labels <= n_files),
  sealed_at timestamptz not null,
  sealed_by text not null);

create table hidden_seal_runs (
  id bigint generated by default as identity primary key,
  seal_name text not null references hidden_seals(name),
  answer_sha256 text not null check (answer_sha256 ~ '^[0-9a-f]{64}$'),
  model_version text not null check (length(model_version) between 1 and 200),
  committed_at timestamptz not null,
  committed_by text not null,
  unique (seal_name, answer_sha256));
create index ix_hidden_seal_runs_seal on hidden_seal_runs(seal_name);

create trigger hidden_seals_append_only before update or delete on hidden_seals for each row execute function forbid_mutation();
create trigger hidden_seals_no_truncate before truncate on hidden_seals for each statement execute function forbid_mutation();
create trigger hidden_seal_runs_append_only before update or delete on hidden_seal_runs for each row execute function forbid_mutation();
create trigger hidden_seal_runs_no_truncate before truncate on hidden_seal_runs for each statement execute function forbid_mutation();

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'inspector_app') then
    revoke update, delete, truncate on hidden_seals, hidden_seal_runs from inspector_app;
  end if;
end $$;
