-- 0010 — журнал отказов в приёме файлов (T-120, OS-INSP-1.2.35).
-- Отчёт о целостности пакета называет по каждому файлу реестра, что с ним стало. Принятый файл лежит в files, а отказ
-- до сих пор жил только в ответе на загрузку и строкой в аудите. Здесь — код, сообщение и файл-оригинал для дубля по
-- содержимому (OS-INSP-1.2.33). Журнал только дописывается. Миграция неизменяема: правка — только новым файлом.
-- Номер — следующий свободный на момент слияния в main (раннер требует нумерацию без пропусков; T-135 и T-134 тоже несут миграции).

create table file_rejections (
  id bigint generated by default as identity primary key,
  inspection_id text not null references inspections(id),
  file_name text not null,
  code text not null,
  message text not null,
  duplicate_of text,
  created_at timestamptz not null
);
create index ix_file_rejections_insp on file_rejections(inspection_id);

create trigger file_rejections_append_only before update or delete on file_rejections for each row execute function forbid_mutation();
create trigger file_rejections_no_truncate before truncate on file_rejections for each statement execute function forbid_mutation();

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'inspector_app') then
    grant select, insert on file_rejections to inspector_app;
    revoke update, delete, truncate on file_rejections from inspector_app;
  end if;
end $$;
