-- 0014 — слой L8 после оператора сравнения (T-177, ADR-0008 п. 2; OS-INSP-3.1.70–3.1.89, 1.5.2–1.5.9).
-- 1) Отметки изменений на листах из ответа ML /analyze (CMP-29): облако ревизии и выноска «Изм. N» (IDN-04),
--    строка таблицы изменений основной надписи (IDN-03). Пишутся при разборе файла, как реквизиты и скрытые работы.
-- 2) Доказательная группа хранит след слоя L8 (проверки, понижения, причина), ссылку на согласованное изменение
--    (approved_change_ref поля GOLD; 'NONE' — искали, не нашли) и корень каскада VER-12 (derived_from).
-- Миграция неизменяема: правка — только новым файлом. Номер — следующий свободный на момент влития.

create table change_marks (
  id bigint generated by default as identity primary key,
  file_id text not null references files(id),
  page integer not null,
  kind text not null check (kind in ('cloud', 'callout', 'stamp_row')),
  number text,
  bbox_json json,
  text text not null default ''
);
create index ix_change_marks_file on change_marks(file_id);

alter table checks add column l8_json json;
alter table checks add column approved_change_ref text;
alter table checks add column derived_from text;
