-- Separate human annotations: no changes to inspector decisions or processing results.
alter table users drop constraint users_role_ck;
alter table users add constraint users_role_ck check (role in ('inspector','supervisor','admin','ml_engineer','curator','verifier'));

create table verification_ingestions (
  id text primary key, source_version text not null, author text references users(id),
  cursor_json jsonb not null default '{}', inventory_json jsonb not null default '{}',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table verification_tasks (
  id text primary key, fingerprint text unique not null, parameter text not null references params(code),
  operation text not null check (operation in ('reading','field_match','comparison','missing')),
  question text not null, snapshot_json jsonb not null, difficulty text not null check (difficulty in ('ordinary','hard','control')),
  source_version text not null, object_key text not null, random_key double precision not null,
  state text not null default 'ready' check (state in ('ready','claimed','answered','retired')),
  required_reviews integer not null default 1 check(required_reviews between 1 and 3),
  review_count integer not null default 0, created_at timestamptz not null default now()
);
create index verification_tasks_ready on verification_tasks(parameter,difficulty,random_key) where state='ready';
create table verification_assignments (
  id text primary key, task_id text not null references verification_tasks(id), user_id text not null references users(id),
  token text not null, expires_at timestamptz not null, created_at timestamptz not null,
  purpose text not null default 'annotation' check(purpose in ('annotation','review')),
  state text not null default 'active' check(state in ('active','expired','submitted'))
);
create unique index verification_one_active_per_user on verification_assignments(user_id) where state='active';
create unique index verification_one_active_per_task on verification_assignments(task_id) where state='active';
create index verification_expiring on verification_assignments(expires_at) where state='active';
create table verification_labels (
  id text primary key, assignment_id text unique not null references verification_assignments(id),
  task_id text not null references verification_tasks(id), user_id text not null references users(id),
  answer text not null check(answer in ('YES','NO','UNSURE')), comment text not null, corrected_value text,
  idempotency_key text not null, request_digest text not null, created_at timestamptz not null,
  unique(user_id,idempotency_key), unique(task_id,user_id)
);
create table verification_adjudications (
  id bigint generated by default as identity primary key, task_id text not null references verification_tasks(id),
  author text not null references users(id), answer text not null check(answer in ('YES','NO','UNSURE')),
  corrected_value text, comment text not null, created_at timestamptz not null default now()
);
create table verification_coverage (
  parameter text primary key references params(code), ready integer not null default 0,
  answered integer not null default 0, yes integer not null default 0, no integer not null default 0, unsure integer not null default 0
);
create table verification_datasets (
  id text primary key, author text not null references users(id), manifest_json jsonb not null,
  digest text not null, created_at timestamptz not null default now()
);
create table verification_dataset_items (
  dataset_id text not null references verification_datasets(id), task_id text not null references verification_tasks(id),
  snapshot_json jsonb not null, split text not null check(split in ('train','validation','test')), primary key(dataset_id,task_id)
);
create trigger verification_labels_append_only before update or delete on verification_labels for each row execute function forbid_mutation();
create trigger verification_adjudications_append_only before update or delete on verification_adjudications for each row execute function forbid_mutation();
create trigger verification_datasets_append_only before update or delete on verification_datasets for each row execute function forbid_mutation();
create trigger verification_dataset_items_append_only before update or delete on verification_dataset_items for each row execute function forbid_mutation();

create function verification_snapshot_guard() returns trigger language plpgsql as $$
begin
 if (to_jsonb(new)-'state'-'review_count') is distinct from (to_jsonb(old)-'state'-'review_count') then
   raise exception 'Task evidence is immutable';
 end if;
 return new;
end $$;
create trigger verification_task_snapshot before update on verification_tasks for each row execute function verification_snapshot_guard();
create trigger verification_task_delete before delete on verification_tasks for each row execute function forbid_mutation();
create trigger verification_labels_no_truncate before truncate on verification_labels for each statement execute function forbid_mutation();
create trigger verification_adjudications_no_truncate before truncate on verification_adjudications for each statement execute function forbid_mutation();
create trigger verification_datasets_no_truncate before truncate on verification_datasets for each statement execute function forbid_mutation();
create trigger verification_dataset_items_no_truncate before truncate on verification_dataset_items for each statement execute function forbid_mutation();
